# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\My_Github\Python\ssq\ssq_ui\ssq_main.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 615)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 330, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(12, 471, 16, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(11, 521, 16, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.dan_lcd_0 = QtWidgets.QLCDNumber(Form)
        self.dan_lcd_0.setGeometry(QtCore.QRect(31, 471, 64, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dan_lcd_0.setFont(font)
        self.dan_lcd_0.setObjectName("dan_lcd_0")
        self.dan_lcd_1 = QtWidgets.QLCDNumber(Form)
        self.dan_lcd_1.setGeometry(QtCore.QRect(101, 471, 64, 23))
        self.dan_lcd_1.setObjectName("dan_lcd_1")
        self.tuo_lcd_0 = QtWidgets.QLCDNumber(Form)
        self.tuo_lcd_0.setGeometry(QtCore.QRect(30, 521, 64, 23))
        self.tuo_lcd_0.setObjectName("tuo_lcd_0")
        self.tuo_lcd_1 = QtWidgets.QLCDNumber(Form)
        self.tuo_lcd_1.setGeometry(QtCore.QRect(100, 521, 64, 23))
        self.tuo_lcd_1.setObjectName("tuo_lcd_1")
        self.tuo_lcd_2 = QtWidgets.QLCDNumber(Form)
        self.tuo_lcd_2.setGeometry(QtCore.QRect(170, 521, 64, 23))
        self.tuo_lcd_2.setObjectName("tuo_lcd_2")
        self.tuo_lcd_3 = QtWidgets.QLCDNumber(Form)
        self.tuo_lcd_3.setGeometry(QtCore.QRect(240, 521, 64, 23))
        self.tuo_lcd_3.setObjectName("tuo_lcd_3")
        self.tuo_lcd_4 = QtWidgets.QLCDNumber(Form)
        self.tuo_lcd_4.setGeometry(QtCore.QRect(310, 521, 64, 23))
        self.tuo_lcd_4.setObjectName("tuo_lcd_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(11, 571, 16, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lan_lcd = QtWidgets.QLCDNumber(Form)
        self.lan_lcd.setGeometry(QtCore.QRect(30, 571, 64, 23))
        self.lan_lcd.setObjectName("lan_lcd")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 520, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 469, 122))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.t_15 = QtWidgets.QToolButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/r_15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_15.setIcon(icon)
        self.t_15.setIconSize(QtCore.QSize(30, 30))
        self.t_15.setObjectName("t_15")
        self.gridLayout_2.addWidget(self.t_15, 1, 3, 1, 1)
        self.t_12 = QtWidgets.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/r_12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_12.setIcon(icon1)
        self.t_12.setIconSize(QtCore.QSize(30, 30))
        self.t_12.setObjectName("t_12")
        self.gridLayout_2.addWidget(self.t_12, 1, 0, 1, 1)
        self.t_24 = QtWidgets.QToolButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/r_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_24.setIcon(icon2)
        self.t_24.setIconSize(QtCore.QSize(30, 30))
        self.t_24.setObjectName("t_24")
        self.gridLayout_2.addWidget(self.t_24, 2, 1, 1, 1)
        self.t_23 = QtWidgets.QToolButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/r_23.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_23.setIcon(icon3)
        self.t_23.setIconSize(QtCore.QSize(30, 30))
        self.t_23.setObjectName("t_23")
        self.gridLayout_2.addWidget(self.t_23, 2, 0, 1, 1)
        self.t_25 = QtWidgets.QToolButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/r_25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_25.setIcon(icon4)
        self.t_25.setIconSize(QtCore.QSize(30, 30))
        self.t_25.setObjectName("t_25")
        self.gridLayout_2.addWidget(self.t_25, 2, 2, 1, 1)
        self.t_14 = QtWidgets.QToolButton(self.layoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/r_14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_14.setIcon(icon5)
        self.t_14.setIconSize(QtCore.QSize(30, 30))
        self.t_14.setObjectName("t_14")
        self.gridLayout_2.addWidget(self.t_14, 1, 2, 1, 1)
        self.t_13 = QtWidgets.QToolButton(self.layoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/r_13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_13.setIcon(icon6)
        self.t_13.setIconSize(QtCore.QSize(30, 30))
        self.t_13.setObjectName("t_13")
        self.gridLayout_2.addWidget(self.t_13, 1, 1, 1, 1)
        self.t_26 = QtWidgets.QToolButton(self.layoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/r_26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_26.setIcon(icon7)
        self.t_26.setIconSize(QtCore.QSize(30, 30))
        self.t_26.setObjectName("t_26")
        self.gridLayout_2.addWidget(self.t_26, 2, 3, 1, 1)
        self.t_19 = QtWidgets.QToolButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/r_19.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_19.setIcon(icon8)
        self.t_19.setIconSize(QtCore.QSize(30, 30))
        self.t_19.setObjectName("t_19")
        self.gridLayout_2.addWidget(self.t_19, 1, 7, 1, 1)
        self.t_05 = QtWidgets.QToolButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/r_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_05.setIcon(icon9)
        self.t_05.setIconSize(QtCore.QSize(30, 30))
        self.t_05.setObjectName("t_05")
        self.gridLayout_2.addWidget(self.t_05, 0, 4, 1, 1)
        self.t_21 = QtWidgets.QToolButton(self.layoutWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/r_21.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_21.setIcon(icon10)
        self.t_21.setIconSize(QtCore.QSize(30, 30))
        self.t_21.setObjectName("t_21")
        self.gridLayout_2.addWidget(self.t_21, 1, 9, 1, 1)
        self.t_08 = QtWidgets.QToolButton(self.layoutWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/r_8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_08.setIcon(icon11)
        self.t_08.setIconSize(QtCore.QSize(30, 30))
        self.t_08.setObjectName("t_08")
        self.gridLayout_2.addWidget(self.t_08, 0, 7, 1, 1)
        self.t_28 = QtWidgets.QToolButton(self.layoutWidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/r_28.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_28.setIcon(icon12)
        self.t_28.setIconSize(QtCore.QSize(30, 30))
        self.t_28.setObjectName("t_28")
        self.gridLayout_2.addWidget(self.t_28, 2, 5, 1, 1)
        self.t_04 = QtWidgets.QToolButton(self.layoutWidget)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/r_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_04.setIcon(icon13)
        self.t_04.setIconSize(QtCore.QSize(30, 30))
        self.t_04.setObjectName("t_04")
        self.gridLayout_2.addWidget(self.t_04, 0, 3, 1, 1)
        self.t_27 = QtWidgets.QToolButton(self.layoutWidget)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/r_27.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_27.setIcon(icon14)
        self.t_27.setIconSize(QtCore.QSize(30, 30))
        self.t_27.setObjectName("t_27")
        self.gridLayout_2.addWidget(self.t_27, 2, 4, 1, 1)
        self.t_22 = QtWidgets.QToolButton(self.layoutWidget)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/r_22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_22.setIcon(icon15)
        self.t_22.setIconSize(QtCore.QSize(30, 30))
        self.t_22.setObjectName("t_22")
        self.gridLayout_2.addWidget(self.t_22, 1, 10, 1, 1)
        self.t_29 = QtWidgets.QToolButton(self.layoutWidget)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/r_29.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_29.setIcon(icon16)
        self.t_29.setIconSize(QtCore.QSize(30, 30))
        self.t_29.setObjectName("t_29")
        self.gridLayout_2.addWidget(self.t_29, 2, 6, 1, 1)
        self.t_18 = QtWidgets.QToolButton(self.layoutWidget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/r_18.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_18.setIcon(icon17)
        self.t_18.setIconSize(QtCore.QSize(30, 30))
        self.t_18.setObjectName("t_18")
        self.gridLayout_2.addWidget(self.t_18, 1, 6, 1, 1)
        self.t_30 = QtWidgets.QToolButton(self.layoutWidget)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/r_30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_30.setIcon(icon18)
        self.t_30.setIconSize(QtCore.QSize(30, 30))
        self.t_30.setObjectName("t_30")
        self.gridLayout_2.addWidget(self.t_30, 2, 7, 1, 1)
        self.t_33 = QtWidgets.QToolButton(self.layoutWidget)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/r_33.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_33.setIcon(icon19)
        self.t_33.setIconSize(QtCore.QSize(30, 30))
        self.t_33.setObjectName("t_33")
        self.gridLayout_2.addWidget(self.t_33, 2, 10, 1, 1)
        self.t_10 = QtWidgets.QToolButton(self.layoutWidget)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/r_10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_10.setIcon(icon20)
        self.t_10.setIconSize(QtCore.QSize(30, 30))
        self.t_10.setObjectName("t_10")
        self.gridLayout_2.addWidget(self.t_10, 0, 9, 1, 1)
        self.t_06 = QtWidgets.QToolButton(self.layoutWidget)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/r_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_06.setIcon(icon21)
        self.t_06.setIconSize(QtCore.QSize(30, 30))
        self.t_06.setObjectName("t_06")
        self.gridLayout_2.addWidget(self.t_06, 0, 5, 1, 1)
        self.t_17 = QtWidgets.QToolButton(self.layoutWidget)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/r_17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_17.setIcon(icon22)
        self.t_17.setIconSize(QtCore.QSize(30, 30))
        self.t_17.setObjectName("t_17")
        self.gridLayout_2.addWidget(self.t_17, 1, 5, 1, 1)
        self.t_20 = QtWidgets.QToolButton(self.layoutWidget)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/r_20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_20.setIcon(icon23)
        self.t_20.setIconSize(QtCore.QSize(30, 30))
        self.t_20.setObjectName("t_20")
        self.gridLayout_2.addWidget(self.t_20, 1, 8, 1, 1)
        self.t_07 = QtWidgets.QToolButton(self.layoutWidget)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/r_7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_07.setIcon(icon24)
        self.t_07.setIconSize(QtCore.QSize(30, 30))
        self.t_07.setObjectName("t_07")
        self.gridLayout_2.addWidget(self.t_07, 0, 6, 1, 1)
        self.t_16 = QtWidgets.QToolButton(self.layoutWidget)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/r_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_16.setIcon(icon25)
        self.t_16.setIconSize(QtCore.QSize(30, 30))
        self.t_16.setObjectName("t_16")
        self.gridLayout_2.addWidget(self.t_16, 1, 4, 1, 1)
        self.t_32 = QtWidgets.QToolButton(self.layoutWidget)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/r_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_32.setIcon(icon26)
        self.t_32.setIconSize(QtCore.QSize(30, 30))
        self.t_32.setObjectName("t_32")
        self.gridLayout_2.addWidget(self.t_32, 2, 9, 1, 1)
        self.t_11 = QtWidgets.QToolButton(self.layoutWidget)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/r_11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_11.setIcon(icon27)
        self.t_11.setIconSize(QtCore.QSize(30, 30))
        self.t_11.setObjectName("t_11")
        self.gridLayout_2.addWidget(self.t_11, 0, 10, 1, 1)
        self.t_02 = QtWidgets.QToolButton(self.layoutWidget)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/r_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_02.setIcon(icon28)
        self.t_02.setIconSize(QtCore.QSize(30, 30))
        self.t_02.setObjectName("t_02")
        self.gridLayout_2.addWidget(self.t_02, 0, 1, 1, 1)
        self.t_09 = QtWidgets.QToolButton(self.layoutWidget)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/r_9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_09.setIcon(icon29)
        self.t_09.setIconSize(QtCore.QSize(30, 30))
        self.t_09.setObjectName("t_09")
        self.gridLayout_2.addWidget(self.t_09, 0, 8, 1, 1)
        self.t_03 = QtWidgets.QToolButton(self.layoutWidget)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/r_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_03.setIcon(icon30)
        self.t_03.setIconSize(QtCore.QSize(30, 30))
        self.t_03.setObjectName("t_03")
        self.gridLayout_2.addWidget(self.t_03, 0, 2, 1, 1)
        self.t_01 = QtWidgets.QToolButton(self.layoutWidget)
        self.t_01.setAutoFillBackground(False)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/r_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_01.setIcon(icon31)
        self.t_01.setIconSize(QtCore.QSize(30, 30))
        self.t_01.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.t_01.setAutoRaise(False)
        self.t_01.setObjectName("t_01")
        self.gridLayout_2.addWidget(self.t_01, 0, 0, 1, 1)
        self.t_31 = QtWidgets.QToolButton(self.layoutWidget)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/r_31.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_31.setIcon(icon32)
        self.t_31.setIconSize(QtCore.QSize(30, 30))
        self.t_31.setObjectName("t_31")
        self.gridLayout_2.addWidget(self.t_31, 2, 8, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 370, 340, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.b_6 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/b_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_6.setIcon(icon33)
        self.b_6.setIconSize(QtCore.QSize(30, 30))
        self.b_6.setObjectName("b_6")
        self.gridLayout_3.addWidget(self.b_6, 0, 5, 1, 1)
        self.b_5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/b_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_5.setIcon(icon34)
        self.b_5.setIconSize(QtCore.QSize(30, 30))
        self.b_5.setObjectName("b_5")
        self.gridLayout_3.addWidget(self.b_5, 0, 4, 1, 1)
        self.b_8 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/b_8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_8.setIcon(icon35)
        self.b_8.setIconSize(QtCore.QSize(30, 30))
        self.b_8.setObjectName("b_8")
        self.gridLayout_3.addWidget(self.b_8, 0, 7, 1, 1)
        self.b_7 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/b_7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_7.setIcon(icon36)
        self.b_7.setIconSize(QtCore.QSize(30, 30))
        self.b_7.setObjectName("b_7")
        self.gridLayout_3.addWidget(self.b_7, 0, 6, 1, 1)
        self.b_14 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/b_14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_14.setIcon(icon37)
        self.b_14.setIconSize(QtCore.QSize(30, 30))
        self.b_14.setObjectName("b_14")
        self.gridLayout_3.addWidget(self.b_14, 1, 5, 1, 1)
        self.b_3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/b_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_3.setIcon(icon38)
        self.b_3.setIconSize(QtCore.QSize(30, 30))
        self.b_3.setObjectName("b_3")
        self.gridLayout_3.addWidget(self.b_3, 0, 2, 1, 1)
        self.b_2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/b_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_2.setIcon(icon39)
        self.b_2.setIconSize(QtCore.QSize(30, 30))
        self.b_2.setObjectName("b_2")
        self.gridLayout_3.addWidget(self.b_2, 0, 1, 1, 1)
        self.b_4 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/b_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_4.setIcon(icon40)
        self.b_4.setIconSize(QtCore.QSize(30, 30))
        self.b_4.setObjectName("b_4")
        self.gridLayout_3.addWidget(self.b_4, 0, 3, 1, 1)
        self.b_1 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/b_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_1.setIcon(icon41)
        self.b_1.setIconSize(QtCore.QSize(30, 30))
        self.b_1.setObjectName("b_1")
        self.gridLayout_3.addWidget(self.b_1, 0, 0, 1, 1)
        self.b_9 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/b_9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_9.setIcon(icon42)
        self.b_9.setIconSize(QtCore.QSize(30, 30))
        self.b_9.setObjectName("b_9")
        self.gridLayout_3.addWidget(self.b_9, 1, 0, 1, 1)
        self.b_10 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/b_10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_10.setIcon(icon43)
        self.b_10.setIconSize(QtCore.QSize(30, 30))
        self.b_10.setObjectName("b_10")
        self.gridLayout_3.addWidget(self.b_10, 1, 1, 1, 1)
        self.b_11 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/b_11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_11.setIcon(icon44)
        self.b_11.setIconSize(QtCore.QSize(30, 30))
        self.b_11.setObjectName("b_11")
        self.gridLayout_3.addWidget(self.b_11, 1, 2, 1, 1)
        self.b_12 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/b_12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_12.setIcon(icon45)
        self.b_12.setIconSize(QtCore.QSize(30, 30))
        self.b_12.setObjectName("b_12")
        self.gridLayout_3.addWidget(self.b_12, 1, 3, 1, 1)
        self.b_13 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/b_13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_13.setIcon(icon46)
        self.b_13.setIconSize(QtCore.QSize(30, 30))
        self.b_13.setObjectName("b_13")
        self.gridLayout_3.addWidget(self.b_13, 1, 4, 1, 1)
        self.b_15 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/b_15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_15.setIcon(icon47)
        self.b_15.setIconSize(QtCore.QSize(30, 30))
        self.b_15.setObjectName("b_15")
        self.gridLayout_3.addWidget(self.b_15, 1, 6, 1, 1)
        self.b_16 = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/b_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_16.setIcon(icon48)
        self.b_16.setIconSize(QtCore.QSize(30, 30))
        self.b_16.setObjectName("b_16")
        self.gridLayout_3.addWidget(self.b_16, 1, 7, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 491, 139))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.d_15 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_15.setIcon(icon)
        self.d_15.setIconSize(QtCore.QSize(30, 30))
        self.d_15.setObjectName("d_15")
        self.gridLayout.addWidget(self.d_15, 1, 3, 1, 1)
        self.d_12 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_12.setIcon(icon1)
        self.d_12.setIconSize(QtCore.QSize(30, 30))
        self.d_12.setObjectName("d_12")
        self.gridLayout.addWidget(self.d_12, 1, 0, 1, 1)
        self.d_24 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_24.setIcon(icon2)
        self.d_24.setIconSize(QtCore.QSize(30, 30))
        self.d_24.setObjectName("d_24")
        self.gridLayout.addWidget(self.d_24, 2, 1, 1, 1)
        self.d_23 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_23.setIcon(icon3)
        self.d_23.setIconSize(QtCore.QSize(30, 30))
        self.d_23.setObjectName("d_23")
        self.gridLayout.addWidget(self.d_23, 2, 0, 1, 1)
        self.d_25 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_25.setIcon(icon4)
        self.d_25.setIconSize(QtCore.QSize(30, 30))
        self.d_25.setObjectName("d_25")
        self.gridLayout.addWidget(self.d_25, 2, 2, 1, 1)
        self.d_14 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_14.setIcon(icon5)
        self.d_14.setIconSize(QtCore.QSize(30, 30))
        self.d_14.setObjectName("d_14")
        self.gridLayout.addWidget(self.d_14, 1, 2, 1, 1)
        self.d_13 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_13.setIcon(icon6)
        self.d_13.setIconSize(QtCore.QSize(30, 30))
        self.d_13.setObjectName("d_13")
        self.gridLayout.addWidget(self.d_13, 1, 1, 1, 1)
        self.d_26 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_26.setIcon(icon7)
        self.d_26.setIconSize(QtCore.QSize(30, 30))
        self.d_26.setObjectName("d_26")
        self.gridLayout.addWidget(self.d_26, 2, 3, 1, 1)
        self.d_19 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_19.setIcon(icon8)
        self.d_19.setIconSize(QtCore.QSize(30, 30))
        self.d_19.setObjectName("d_19")
        self.gridLayout.addWidget(self.d_19, 1, 7, 1, 1)
        self.d_05 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_05.setIcon(icon9)
        self.d_05.setIconSize(QtCore.QSize(30, 30))
        self.d_05.setObjectName("d_05")
        self.gridLayout.addWidget(self.d_05, 0, 4, 1, 1)
        self.d_21 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_21.setIcon(icon10)
        self.d_21.setIconSize(QtCore.QSize(30, 30))
        self.d_21.setObjectName("d_21")
        self.gridLayout.addWidget(self.d_21, 1, 9, 1, 1)
        self.d_08 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_08.setIcon(icon11)
        self.d_08.setIconSize(QtCore.QSize(30, 30))
        self.d_08.setObjectName("d_08")
        self.gridLayout.addWidget(self.d_08, 0, 7, 1, 1)
        self.d_28 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_28.setIcon(icon12)
        self.d_28.setIconSize(QtCore.QSize(30, 30))
        self.d_28.setObjectName("d_28")
        self.gridLayout.addWidget(self.d_28, 2, 5, 1, 1)
        self.d_04 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_04.setIcon(icon13)
        self.d_04.setIconSize(QtCore.QSize(30, 30))
        self.d_04.setObjectName("d_04")
        self.gridLayout.addWidget(self.d_04, 0, 3, 1, 1)
        self.d_27 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_27.setIcon(icon14)
        self.d_27.setIconSize(QtCore.QSize(30, 30))
        self.d_27.setObjectName("d_27")
        self.gridLayout.addWidget(self.d_27, 2, 4, 1, 1)
        self.d_22 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_22.setIcon(icon15)
        self.d_22.setIconSize(QtCore.QSize(30, 30))
        self.d_22.setObjectName("d_22")
        self.gridLayout.addWidget(self.d_22, 1, 10, 1, 1)
        self.d_29 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_29.setIcon(icon16)
        self.d_29.setIconSize(QtCore.QSize(30, 30))
        self.d_29.setObjectName("d_29")
        self.gridLayout.addWidget(self.d_29, 2, 6, 1, 1)
        self.d_18 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_18.setIcon(icon17)
        self.d_18.setIconSize(QtCore.QSize(30, 30))
        self.d_18.setObjectName("d_18")
        self.gridLayout.addWidget(self.d_18, 1, 6, 1, 1)
        self.d_30 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_30.setIcon(icon18)
        self.d_30.setIconSize(QtCore.QSize(30, 30))
        self.d_30.setObjectName("d_30")
        self.gridLayout.addWidget(self.d_30, 2, 7, 1, 1)
        self.d_33 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_33.setIcon(icon19)
        self.d_33.setIconSize(QtCore.QSize(30, 30))
        self.d_33.setObjectName("d_33")
        self.gridLayout.addWidget(self.d_33, 2, 10, 1, 1)
        self.d_10 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_10.setIcon(icon20)
        self.d_10.setIconSize(QtCore.QSize(30, 30))
        self.d_10.setObjectName("d_10")
        self.gridLayout.addWidget(self.d_10, 0, 9, 1, 1)
        self.d_06 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_06.setIcon(icon21)
        self.d_06.setIconSize(QtCore.QSize(30, 30))
        self.d_06.setObjectName("d_06")
        self.gridLayout.addWidget(self.d_06, 0, 5, 1, 1)
        self.d_17 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_17.setIcon(icon22)
        self.d_17.setIconSize(QtCore.QSize(30, 30))
        self.d_17.setObjectName("d_17")
        self.gridLayout.addWidget(self.d_17, 1, 5, 1, 1)
        self.d_20 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_20.setIcon(icon23)
        self.d_20.setIconSize(QtCore.QSize(30, 30))
        self.d_20.setObjectName("d_20")
        self.gridLayout.addWidget(self.d_20, 1, 8, 1, 1)
        self.d_07 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_07.setIcon(icon24)
        self.d_07.setIconSize(QtCore.QSize(30, 30))
        self.d_07.setObjectName("d_07")
        self.gridLayout.addWidget(self.d_07, 0, 6, 1, 1)
        self.d_16 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_16.setIcon(icon25)
        self.d_16.setIconSize(QtCore.QSize(30, 30))
        self.d_16.setObjectName("d_16")
        self.gridLayout.addWidget(self.d_16, 1, 4, 1, 1)
        self.d_32 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_32.setIcon(icon26)
        self.d_32.setIconSize(QtCore.QSize(30, 30))
        self.d_32.setObjectName("d_32")
        self.gridLayout.addWidget(self.d_32, 2, 9, 1, 1)
        self.d_11 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_11.setIcon(icon27)
        self.d_11.setIconSize(QtCore.QSize(30, 30))
        self.d_11.setObjectName("d_11")
        self.gridLayout.addWidget(self.d_11, 0, 10, 1, 1)
        self.d_02 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_02.setIcon(icon28)
        self.d_02.setIconSize(QtCore.QSize(30, 30))
        self.d_02.setObjectName("d_02")
        self.gridLayout.addWidget(self.d_02, 0, 1, 1, 1)
        self.d_09 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_09.setIcon(icon29)
        self.d_09.setIconSize(QtCore.QSize(30, 30))
        self.d_09.setObjectName("d_09")
        self.gridLayout.addWidget(self.d_09, 0, 8, 1, 1)
        self.d_03 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_03.setIcon(icon30)
        self.d_03.setIconSize(QtCore.QSize(30, 30))
        self.d_03.setObjectName("d_03")
        self.gridLayout.addWidget(self.d_03, 0, 2, 1, 1)
        self.d_01 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_01.setAutoFillBackground(False)
        self.d_01.setIcon(icon31)
        self.d_01.setIconSize(QtCore.QSize(30, 30))
        self.d_01.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.d_01.setAutoRaise(False)
        self.d_01.setArrowType(QtCore.Qt.NoArrow)
        self.d_01.setObjectName("d_01")
        self.gridLayout.addWidget(self.d_01, 0, 0, 1, 1)
        self.d_31 = QtWidgets.QToolButton(self.layoutWidget1)
        self.d_31.setIcon(icon32)
        self.d_31.setIconSize(QtCore.QSize(30, 30))
        self.d_31.setObjectName("d_31")
        self.gridLayout.addWidget(self.d_31, 2, 8, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "胆拖计算器"))
        self.label.setText(_translate("Form", "红球胆码"))
        self.label_2.setText(_translate("Form", "蓝球"))
        self.label_3.setText(_translate("Form", "红球拖码"))
        self.label_4.setText(_translate("Form", "胆"))
        self.label_5.setText(_translate("Form", "拖"))
        self.label_6.setText(_translate("Form", "蓝"))
        self.pushButton.setText(_translate("Form", "投注"))
        self.t_15.setText(_translate("Form", "15"))
        self.t_12.setText(_translate("Form", "12"))
        self.t_24.setText(_translate("Form", "24"))
        self.t_23.setText(_translate("Form", "23"))
        self.t_25.setText(_translate("Form", "25"))
        self.t_14.setText(_translate("Form", "14"))
        self.t_13.setText(_translate("Form", "13"))
        self.t_26.setText(_translate("Form", "26"))
        self.t_19.setText(_translate("Form", "19"))
        self.t_05.setText(_translate("Form", "05"))
        self.t_21.setText(_translate("Form", "21"))
        self.t_08.setText(_translate("Form", "08"))
        self.t_28.setText(_translate("Form", "28"))
        self.t_04.setText(_translate("Form", "04"))
        self.t_27.setText(_translate("Form", "27"))
        self.t_22.setText(_translate("Form", "22"))
        self.t_29.setText(_translate("Form", "29"))
        self.t_18.setText(_translate("Form", "18"))
        self.t_30.setText(_translate("Form", "30"))
        self.t_33.setText(_translate("Form", "33"))
        self.t_10.setText(_translate("Form", "10"))
        self.t_06.setText(_translate("Form", "06"))
        self.t_17.setText(_translate("Form", "17"))
        self.t_20.setText(_translate("Form", "20"))
        self.t_07.setText(_translate("Form", "07"))
        self.t_16.setText(_translate("Form", "16"))
        self.t_32.setText(_translate("Form", "32"))
        self.t_11.setText(_translate("Form", "11"))
        self.t_02.setText(_translate("Form", "02"))
        self.t_09.setText(_translate("Form", "09"))
        self.t_03.setText(_translate("Form", "03"))
        self.t_01.setText(_translate("Form", "01"))
        self.t_31.setText(_translate("Form", "31"))
        self.b_6.setText(_translate("Form", "6"))
        self.b_5.setText(_translate("Form", "5"))
        self.b_8.setText(_translate("Form", "8"))
        self.b_7.setText(_translate("Form", "7"))
        self.b_14.setText(_translate("Form", "14"))
        self.b_3.setText(_translate("Form", "3"))
        self.b_2.setText(_translate("Form", "2"))
        self.b_4.setText(_translate("Form", "4"))
        self.b_1.setText(_translate("Form", "1"))
        self.b_9.setText(_translate("Form", "9"))
        self.b_10.setText(_translate("Form", "10"))
        self.b_11.setText(_translate("Form", "11"))
        self.b_12.setText(_translate("Form", "12"))
        self.b_13.setText(_translate("Form", "13"))
        self.b_15.setText(_translate("Form", "15"))
        self.b_16.setText(_translate("Form", "16"))
        self.d_15.setText(_translate("Form", "15"))
        self.d_12.setText(_translate("Form", "12"))
        self.d_24.setText(_translate("Form", "24"))
        self.d_23.setText(_translate("Form", "23"))
        self.d_25.setText(_translate("Form", "25"))
        self.d_14.setText(_translate("Form", "14"))
        self.d_13.setText(_translate("Form", "13"))
        self.d_26.setText(_translate("Form", "26"))
        self.d_19.setText(_translate("Form", "19"))
        self.d_05.setText(_translate("Form", "05"))
        self.d_21.setText(_translate("Form", "21"))
        self.d_08.setText(_translate("Form", "08"))
        self.d_28.setText(_translate("Form", "28"))
        self.d_04.setText(_translate("Form", "04"))
        self.d_27.setText(_translate("Form", "27"))
        self.d_22.setText(_translate("Form", "22"))
        self.d_29.setText(_translate("Form", "29"))
        self.d_18.setText(_translate("Form", "18"))
        self.d_30.setText(_translate("Form", "30"))
        self.d_33.setText(_translate("Form", "33"))
        self.d_10.setText(_translate("Form", "10"))
        self.d_06.setText(_translate("Form", "06"))
        self.d_17.setText(_translate("Form", "17"))
        self.d_20.setText(_translate("Form", "20"))
        self.d_07.setText(_translate("Form", "07"))
        self.d_16.setText(_translate("Form", "16"))
        self.d_32.setText(_translate("Form", "32"))
        self.d_11.setText(_translate("Form", "11"))
        self.d_02.setText(_translate("Form", "02"))
        self.d_09.setText(_translate("Form", "09"))
        self.d_03.setText(_translate("Form", "03"))
        self.d_01.setText(_translate("Form", "01"))
        self.d_31.setText(_translate("Form", "31"))

import ssq_ui.ssq_rc
